-- +goose Up

-- dr_public_key holds the vessel's restore-bundle encryption recipient
-- (architecture 12.5, pkg/backupcrypto — an age X25519 public key, plain
-- text, not a secret). Generated by the vessel itself at redemption time
-- (vessel/sync.Redeem) and sent as part of that request — the matching
-- private key never leaves the vessel. NULL for an enrollment redeemed
-- before this column existed, or one still only Issued (never
-- redeemed) — either way, office simply cannot produce a restore bundle
-- for that vessel until it (re-)redeems.
ALTER TABLE enrollments ADD COLUMN dr_public_key TEXT;

-- +goose Down
ALTER TABLE enrollments DROP COLUMN dr_public_key;
