// SPDX-License-Identifier: AGPL-3.0-only

// Package enrollment models the office side of vessel enrollment
// (architecture 12.4, design handoff B2's Enrollment tab): issuing a
// one-time code and a printable enrollment sheet (office URL, code,
// initial Master credentials), revoking or re-issuing at any time, and
// redeeming a code for a long-lived sync credential (architecture 11.2's
// sync handshake — see Redeem and office/synccred, which mints the
// credential itself).
package enrollment

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/captv89/ovl/pkg/authcrypto"
)

// State is where one vessel's enrollment stands.
type State string

const (
	// StateIssued means a code and initial Master credentials have been
	// generated and are waiting to be redeemed by the vessel.
	StateIssued State = "issued"
	// StateEnrolled means the vessel has exchanged its code for a
	// long-lived sync credential (architecture 11.2) via Redeem.
	StateEnrolled State = "enrolled"
	// StateRevoked means an Admin revoked the credential (architecture
	// 12.4: "revoke ... at any time"). The code and initial password
	// hashes are cleared on revoke, not just the state flag, so a
	// revoked code can never still verify.
	StateRevoked State = "revoked"
)

// defaultMasterUsername is used when Issue/Reissue is called with an
// empty username — neither handoff doc names a required initial Master
// username, and "master" already reads as the conventional choice
// (matching vessel/auth's own test fixtures and prose throughout this
// project).
const defaultMasterUsername = "master"

// Enrollment is one vessel's enrollment record. There is at most one per
// vessel (VesselID is the identity) — re-issuing replaces the previous
// code/credentials in place rather than accumulating history, matching
// design handoff B2's "revoke and re-issue credential" (singular).
type Enrollment struct {
	VesselID string
	State    State

	// CodeHash and InitialMasterPasswordHash are argon2id hashes
	// (via pkg/authcrypto) of the one-time secrets shown on the
	// printable sheet — never the plaintext. Reusing the password
	// hasher (rather than a separate fast-hash primitive) is deliberate:
	// issuance is a rare, human-driven Admin action, not a per-request
	// hot path, so argon2id's deliberate CPU/memory cost is irrelevant
	// here, and one hashing primitive for every secret this project
	// stores is simpler than two.
	CodeHash                  string
	InitialMasterUsername     string
	InitialMasterPasswordHash string

	// DRPublicKey is this vessel's restore-bundle encryption recipient
	// (architecture 12.5, pkg/backupcrypto — an age X25519 public key),
	// generated by the vessel itself at redemption time and sent as part
	// of that request (vessel/sync.Redeem) — never a secret, so it's
	// stored in plain text unlike everything else on this struct. Empty
	// for an enrollment redeemed before this field existed; that vessel
	// needs to re-enroll before an office-generated restore bundle can
	// be produced for it.
	DRPublicKey string

	IssuedAt  time.Time
	RevokedAt *time.Time // nil unless State == StateRevoked

	UpdatedAt time.Time
}

// IssueResult carries the one-time plaintext values for the printable
// enrollment sheet (architecture 12.4). Code and InitialMasterPassword
// are never stored anywhere and cannot be recovered later — losing the
// sheet means re-issuing, not re-displaying.
type IssueResult struct {
	Enrollment            *Enrollment
	Code                  string
	InitialMasterPassword string
}

// Issue creates a fresh enrollment for vesselID: a new one-time code and
// initial Master credentials. initialMasterUsername defaults to "master"
// if empty.
func Issue(vesselID, initialMasterUsername string) (*IssueResult, error) {
	if strings.TrimSpace(vesselID) == "" {
		return nil, errors.New("enrollment: vessel id is required")
	}
	e := &Enrollment{VesselID: vesselID}
	return e.Reissue(initialMasterUsername)
}

// Reissue regenerates e's code and initial Master password in place,
// resetting its state to Issued — architecture 12.4's "re-issue at any
// time" applies regardless of e's current state (issued, enrolled, or
// revoked).
func (e *Enrollment) Reissue(initialMasterUsername string) (*IssueResult, error) {
	initialMasterUsername = strings.TrimSpace(initialMasterUsername)
	if initialMasterUsername == "" {
		initialMasterUsername = defaultMasterUsername
	}

	code, err := authcrypto.RandomToken(10) // 80 bits of entropy
	if err != nil {
		return nil, fmt.Errorf("enrollment: generate code: %w", err)
	}
	codeHash, err := authcrypto.HashPassword(code)
	if err != nil {
		return nil, fmt.Errorf("enrollment: hash code: %w", err)
	}

	password, err := authcrypto.RandomToken(12) // 96 bits of entropy
	if err != nil {
		return nil, fmt.Errorf("enrollment: generate initial Master password: %w", err)
	}
	passwordHash, err := authcrypto.HashPassword(password)
	if err != nil {
		return nil, fmt.Errorf("enrollment: hash initial Master password: %w", err)
	}

	now := time.Now().UTC()
	e.State = StateIssued
	e.CodeHash = codeHash
	e.InitialMasterUsername = initialMasterUsername
	e.InitialMasterPasswordHash = passwordHash
	e.IssuedAt = now
	e.RevokedAt = nil
	e.UpdatedAt = now

	return &IssueResult{Enrollment: e, Code: code, InitialMasterPassword: password}, nil
}

// Revoke invalidates e (architecture 12.4: "revoke ... at any time").
// CodeHash is cleared, not just the state flag, so VerifyCode can never
// match again even if a caller forgets to check State first.
func (e *Enrollment) Revoke() {
	now := time.Now().UTC()
	e.State = StateRevoked
	e.CodeHash = ""
	e.RevokedAt = &now
	e.UpdatedAt = now
}

// VerifyCode reports whether code matches e's current code and e is
// still in a redeemable state.
func (e *Enrollment) VerifyCode(code string) (bool, error) {
	if e.State != StateIssued || e.CodeHash == "" {
		return false, nil
	}
	return authcrypto.VerifyPassword(code, e.CodeHash)
}

// ErrCodeNotFound is returned by Redeem when code matches none of the
// candidates given to it.
var ErrCodeNotFound = errors.New("enrollment: code not recognized")

// Redeem finds the Enrollment in candidates whose code matches code,
// transitions it to StateEnrolled, and clears CodeHash so the same
// one-time code cannot be redeemed twice (mirroring Revoke's "clear the
// hash, not just the state flag" rule).
//
// candidates should be every enrollment currently in StateIssued — the
// redemption code is globally unique and self-identifying (Phase 4
// decision, PROJECT.md 2026-07-11's decisions log), so the caller has no
// vessel id to look up by directly, only the code itself. A linear
// argon2id scan is deliberate here: redemption is a one-time,
// human-driven bootstrap action bounded by fleet size, not a repeating
// hot path (contrast office/synccred.Credential.TokenLookupHash, which
// exists precisely because *that* check runs on every SyncService RPC) —
// a second hash primitive purely as a lookup index would cost more
// complexity than this scan ever costs in wall-clock time.
func Redeem(candidates []*Enrollment, code string) (*Enrollment, error) {
	for _, e := range candidates {
		match, err := e.VerifyCode(code)
		if err != nil {
			return nil, err
		}
		if match {
			e.State = StateEnrolled
			e.CodeHash = ""
			e.UpdatedAt = time.Now().UTC()
			return e, nil
		}
	}
	return nil, ErrCodeNotFound
}
