// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type FieldValue struct {
	Name        string   `json:"name"`
	Label       string   `json:"label"`
	Type        string   `json:"type"`
	StringValue *string  `json:"stringValue,omitempty"`
	NumberValue *float64 `json:"numberValue,omitempty"`
	BoolValue   *bool    `json:"boolValue,omitempty"`
}

type Query struct {
}

type ReportFilterInput struct {
	VesselID   *string    `json:"vesselId,omitempty"`
	GroupID    *string    `json:"groupId,omitempty"`
	State      *string    `json:"state,omitempty"`
	EventType  *string    `json:"eventType,omitempty"`
	SchemaName *string    `json:"schemaName,omitempty"`
	DateFrom   *time.Time `json:"dateFrom,omitempty"`
	DateTo     *time.Time `json:"dateTo,omitempty"`
}

type ReportPage struct {
	Items       []*Report `json:"items"`
	HasNextPage bool      `json:"hasNextPage"`
}
